platform :ios, '16.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  settings = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  raise "${settings} must exist. Run flutter pub get before pod install" unless File.file?(settings)
  File.foreach(settings) do |line|
    value = line.match(/^FLUTTER_ROOT=(.+)$/)
    return value[1].strip if value
  end
  raise 'Flutter configuration does not define FLUTTER_ROOT'
end

require File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper')
flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |configuration|
      configuration.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      configuration.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 x86_64'
    end
  end
end
